### ISSUE TITLE
An issue about generating mask

### ISSUE THREAD

**Issue by ShaoTengLiu** [gaochen315/DynamicNeRF#6]
Hi, thanks for your great work.

I am wondering why only consider the foreground as a [person](https://github.com/gaochen315/DynamicNeRF/blob/39085ca1841fe5ee1214e0b46f25705abeb4eddb/utils/generate_data.py#L53).

As shown in the umbrella case, the umbrella is not a person, but also successfully segmented.
![image](https://user-images.githubusercontent.com/51499992/161224240-f04affcc-a5ba-497d-9b4a-ba469ed8beb4.png)
![image](https://user-images.githubusercontent.com/51499992/161224256-063da549-2875-4716-828b-d883182d5766.png)

**Comment by gaochen315** [comment]
Hi @ShaoTengLiu,

The background_mask is only used when calculating camera poses. We do not want to extract features from the points that belong to a person, because it is highly likely that he/she is moving.

In step 6 (Obtain motion mask), we actually define a list of foreground object categories and obtain the coarse foreground mask. It is also worth noting that this coarse foreground mask is only used to initialize the 3D blending weight. Our network will learn to refine the 3D blending weight as training goes.

Hope this helps. Please let me know if there is anything else I can help with. Thanks!

**Comment by ShaoTengLiu** [comment]
Thanks for your reply! It is very clear.
